# os-dash-svc.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: os-dashbd
  name: os-dashbd
spec:
  ports:
    - name: 5601-tcp
      port: 5601
      targetPort: 5601
  selector:
    app: os-dashbd
  type: LoadBalancer
