vpn_packages: # package names may differ between distros
  - wireguard
  - squid
vpn_network:
  name: "myprivnet" # can be anything you want
  ipv4: "10.100.0.1/24"
  ipv4_subnet: "10.100.0.0/24" # VPN IPv4 priv net
  ipv6: "fd01:100::1/64"
  ipv6_subnet: "fd01:100::/64" # VPN IPv6 priv net
  listenport: "51820" # default for wireguard
  saveconfig: "true"
# Your clients will be configured below.
# Remove examples before using. The dummy pubkey may cause config update to fail
vpn_peers:
  - pubkey: "REPLACEME=" # my PC
    allowedips: "10.100.0.2/32, fd01:100::2/128"
  - pubkey: "REPLACEME=" # Another PC
    allowedips: "10.100.0.3/32, fd01:100::3/128"
vpn_proxy_port: "8888"
vpn_proxy_hostname: "vpn-proxy"