apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: name-virtual-host-ingress-matomo
  namespace: matomo
  annotations:
    cert-manager.io/clusterissuer: my-lab-root-issuer
spec:
  ingressClassName: nginx # this is now a required field
  tls:
  - hosts:
    - matomo.example.com
    secretName: mat-ing-cert
  rules:
  - host: matomo.example.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: matomo-svc
            port:
              number: 80
