---
apiVersion: v1
kind: Namespace
metadata:
  name: matomo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matomo-claim
  namespace: matomo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-claim
  namespace: matomo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-passwd
  namespace: matomo
data:
  MARIADB_ROOT_PASSWORD: # encode this value with `echo -n 'my root pass'| base64`
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-user-secret
  namespace: matomo
data:
  MARIADB_USER: # encode this value 1st with `echo -n 'matomo'| base64`
  MARIADB_PASSWORD: # encode this value 1st with `echo -n 'my user pass'| base64`
---
apiVersion: v1
kind: Service
metadata:
  name: matomo-db
  namespace: matomo
spec:
  selector:
    app: matomo-db
  ports:
    - port: 3306
      name: mariadb
---
apiVersion: v1
kind: Service
metadata:
  name: matomo-svc
  namespace: matomo
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: matomo-app
---
apiVersion: v1
kind: Pod
metadata:
  name: matomo-db
  namespace: matomo
  labels:
    app: matomo-db
spec:
  containers:
    - name: matomo-db
      image: mariadb:latest
      env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-passwd
              key: MARIADB_ROOT_PASSWORD
        - name: MARIADB_DATABASE
          value: matomo
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-user-secret
              key: MARIADB_USER
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-secret
              key: MARIADB_PASSWORD

      volumeMounts:
        - mountPath: /var/lib/mysql
          name: dbv
  volumes:
    - name: dbv
      persistentVolumeClaim:
       claimName: db-claim
---
apiVersion: v1
kind: Pod
metadata:
  name: matomo-app
  namespace: matomo
  labels:
    app: matomo-app
spec:
  containers:
    - name: matomo-app
      image: matomo:latest
      env:
        - name: MATOMO_DATABASE_HOST
          value: matomo-db
        - name: MATOMO_DATABASE_ADAPTER
          value: mysql
        - name: MATOMO_DATABASE_TABLES_PREFIX
          value: matomo_
        - name: MATOMO_DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-user-secret
              key: MARIADB_USER
        - name: MATOMO_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-secret
              key: MARIADB_PASSWORD
        - name: MATOMO_DATABASE_DBNAME
          value: matomo
      volumeMounts:
        - mountPath: /var/www/html
          name: matomov
  volumes:
    - name: matomov
      persistentVolumeClaim:
       claimName: matomo-claim
